name: TestButton
template:
  - tag: div
    attributes:
      class: sss
    slots:
      default:
        - text: 1111fffffff
            fsdfjkhsdkjfhdskj
        - tag: el-button
          attributes:
            size: large
            type: success
components:
  el-button:
    packageName: "@vue-cook/element-plus-materials"
    varName: ElButton
